server:
  port: 8666

spring:
  application:
    name: eureka-invocation

eureka:
  instance:
    # 心跳设置，告诉服务器该实例仍在使用
    lease-renewal-interval-in-seconds: 5
    # 告诉服务器如果10秒内未发送任何续约请求，则关闭该客户端
    lease-expiration-duration-in-seconds: 10

  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/, http://127.0.0.1:8762/eureka/
    # 抓取服务列表
    registry-fetch-interval-seconds: 30

# 默认负载均衡器规则
#default:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.boce.controller.MyRule
eureka-service:
  ribbon:
    NFLoadBalancerRuleClassName: com.csdn.conf.MyRule
logging:
  level:
    com.netflix: DEBUG
# 打开feign对hystrix的支持
feign:
  hystrix:
    enabled: true

# 配置hystrix
hystrix:
  threadpool:
    default:
      coreSize: 10  #线程池核心线程数
  command:
    #IService#hello(): 设置某一个接口 default: 设置全部接口
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1000 #超时时间
      circuitBreaker:
        requestVolumeThreshold: 3  #当在配置时间窗口内达到此数量后，进行短路。默认20个
        sleepWindowInMilliseconds: 5  #短路多久以后开始尝试是否恢复，默认5s
        errorThresholdPercentage: 50%  #出错百分比阈值，当达到此阈值后，开始短路。默认50%