server:
  port: 8761
spring:
  profiles: eureka-colony1
  application:
    name: config-server
  cloud:
    config:
      server: 
        git: 
          uri: https://github.com/fymod/easy-spring-cloud/
          search-paths: 07-springcloud-config
          username: 
          password: 
        prefix: /config
eureka:
  instance:
    hostname: eureka-colony1
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://admin:admin@192.168.20.211:8762/eureka/
  server:
    # 关闭自我保护
    enable-self-preservation: false
    # 清理服务器
    eviction-interval-timer-in-ms: 5000
# 日志输出
logging:
  file: log-tms-eureka1/logger.log
  level:
    org.springframework.web: DEBUG

# 关闭程序
endpoints:
  shutdown:
    enabled: true
    sensitive: true

# 关闭项目的安全验证
security:
  user:
    name: admin
    password: admin
    role: SUPERUSER

# 配置关闭程序的路径
management:
  context-path: /tms-eureka
  security:
    roles: SUPERUSER #角色
  port: 8761 # 指定端口
  address: 192.168.20.211 # 指定地址
 
  
---

server:
  port: 8762
spring:
  profiles: eureka-colony2
eureka:
  instance:
    hostname: eureka-colony2
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://admin:admin@192.168.20.211:8761/eureka/
  server:
    # 关闭自我保护
    enable-self-preservation: false
    # 清理服务器
    eviction-interval-timer-in-ms: 5000
# 日志输出
logging:
  file: log-tms-eureka2/logger.log
  level:
    org.springframework.web: DEBUG

# 关闭程序
endpoints:
  shutdown:
    enabled: true
    sensitive: true

# 关闭项目的安全验证
security:
  user:
    name: admin
    password: admin
    role: SUPERUSER

# 配置关闭程序的路径
management:
  context-path: /tms-eureka
  security:
    roles: SUPERUSER #角色
  port: 8762 # 指定端口
  address: 192.168.20.211 # 指定地址