server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
#server:
#  port: 8088
# 
#spring:
#  application:
#    name: tms-send
#  rabbitmq:
#    host: 192.168.20.211
#    port: 15672
#    username: guest
#    password: guest
