spring:
  application:
    name: config-server
  cloud:
    config:
      server: 
        git: 
          uri: https://github.com/keith002/springcloud-eureka/
          search-paths: config
          username: 
          password: 
server:
  port: 8081
eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:admin@localhost:8761/eureka/