spring:
  application:
    name: eureka-service

# 可访问全部敏感端口
# /evn 服务的全部环境变量信息
# /health 当前服务状态
endpoints:
  sensitive: false

eureka:
  instance:
    #心跳设置，告诉服务器该实例仍在使用
    lease-renewal-interval-in-seconds: 5
    #告诉服务器如果10秒内未发送任何续约请求，则关闭该客户端
    lease-expiration-duration-in-seconds: 10
    metadata-map:
      company-name: in
  client:
    serviceUrl:
      defaultZone: http://admin:admin@192.168.20.211:8761/eureka/, http://admin:admin@192.168.20.211:8762/eureka/
    instance-info-replication-interval-seconds: 10

logging:
  level:
    com.netflix: DEBUG